// The hand-seeded launch cohort (doc 04: supply-first, single-metro). This is
// the data a real city would be seeded with before any client sees the app.
import type {
  Booking,
  ChefApplication,
  ChefProfile,
  DB,
  Menu,
  Message,
  Review,
  User,
  WaitlistEntry,
} from "./types";
import { computeQuote } from "./pricing";

function daysFromNow(n: number): string {
  const d = new Date();
  d.setHours(0, 0, 0, 0);
  d.setDate(d.getDate() + n);
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function ts(daysAgo: number): string {
  const d = new Date();
  d.setDate(d.getDate() - daysAgo);
  return d.toISOString();
}

const users: User[] = [
  { id: "user_jordan", email: "jordan@example.com", phone: "+1512000111", fullName: "Jordan Lee", isChef: false, isClient: true, createdAt: ts(60) },
  { id: "user_riley", email: "riley@example.com", fullName: "Riley Chen", isChef: false, isClient: true, createdAt: ts(50) },
  { id: "user_sofia", email: "sofia@example.com", fullName: "Sofia Martín", isChef: false, isClient: true, createdAt: ts(40) },
  { id: "user_ana", email: "ana@example.com", phone: "+1512000222", fullName: "Ana Reyes", isChef: true, isClient: true, createdAt: ts(70) },
  { id: "user_marco", email: "marco@example.com", fullName: "Marco Bianchi", isChef: true, isClient: false, createdAt: ts(68) },
  { id: "user_priya", email: "priya@example.com", fullName: "Priya Nair", isChef: true, isClient: false, createdAt: ts(65) },
  { id: "user_lena", email: "lena@example.com", fullName: "Lena Fischer", isChef: true, isClient: false, createdAt: ts(60) },
  { id: "user_sam", email: "sam@example.com", fullName: "Sam Okafor", isChef: true, isClient: false, createdAt: ts(55) },
  { id: "user_diego", email: "diego@example.com", fullName: "Diego Santos", isChef: true, isClient: false, createdAt: ts(3) },
];

const chefs: ChefProfile[] = [
  {
    id: "chef_ana",
    userId: "user_ana",
    displayName: "Ana Reyes",
    tagline: "Coastal Italian & Mediterranean, cooked in your kitchen",
    bio: "Fifteen years across kitchens in Naples, Barcelona and Austin. I cook bright, seasonal, seafood-forward menus and I love a long table of friends. Everything is made from scratch in your home — you just host.",
    cuisines: ["Italian", "Mediterranean", "Seafood"],
    dietarySpecialties: ["Pescatarian", "Gluten-free on request"],
    serviceCity: "Austin",
    serviceRadiusKm: 30,
    neighborhood: "East Austin",
    maxPartySize: 14,
    travelFee: 40,
    ratingAvg: 4.9,
    ratingCount: 32,
    bookingsCompleted: 34,
    status: "approved",
    foodSafetyCertVerified: true,
    insuranceVerified: true,
    idVerified: true,
    stripeAccountId: "acct_demo_ana",
    stripePayoutsEnabled: true,
    availabilityWeekdays: [4, 5, 6, 0],
    leadTimeDays: 2,
    blockedDates: [],
    seed: "ana",
  },
  {
    id: "chef_marco",
    userId: "user_marco",
    displayName: "Marco Bianchi",
    tagline: "Modern steakhouse & French bistro classics",
    bio: "Former sous chef turned private chef. I bring restaurant-grade technique and a portable grill setup to your patio or kitchen. Big on dry-aged beef, proper sauces, and a great cheese course.",
    cuisines: ["Steakhouse", "French", "American"],
    dietarySpecialties: ["Keto-friendly"],
    serviceCity: "Austin",
    serviceRadiusKm: 25,
    neighborhood: "Westlake",
    maxPartySize: 12,
    travelFee: 50,
    ratingAvg: 4.8,
    ratingCount: 21,
    bookingsCompleted: 22,
    status: "approved",
    foodSafetyCertVerified: true,
    insuranceVerified: true,
    idVerified: true,
    stripeAccountId: "acct_demo_marco",
    stripePayoutsEnabled: true,
    availabilityWeekdays: [5, 6],
    leadTimeDays: 3,
    blockedDates: [],
    seed: "marco",
  },
  {
    id: "chef_priya",
    userId: "user_priya",
    displayName: "Priya Nair",
    tagline: "South Indian & modern vegetarian tasting menus",
    bio: "I cook the food I grew up with in Kerala, reimagined for a dinner party. Deeply vegetarian and vegan-friendly without ever feeling like you're missing out. Spice levels tuned to your table.",
    cuisines: ["South Indian", "Vegetarian", "Vegan"],
    dietarySpecialties: ["Vegan", "Vegetarian", "Nut-free"],
    serviceCity: "Austin",
    serviceRadiusKm: 35,
    neighborhood: "Mueller",
    maxPartySize: 16,
    travelFee: 35,
    ratingAvg: 5.0,
    ratingCount: 18,
    bookingsCompleted: 19,
    status: "approved",
    foodSafetyCertVerified: true,
    insuranceVerified: true,
    idVerified: true,
    stripeAccountId: "acct_demo_priya",
    stripePayoutsEnabled: true,
    availabilityWeekdays: [3, 4, 5, 6],
    leadTimeDays: 2,
    blockedDates: [],
    seed: "priya",
  },
  {
    id: "chef_lena",
    userId: "user_lena",
    displayName: "Lena Fischer",
    tagline: "New American suppers & garden brunches",
    bio: "Seasonal, market-driven cooking with a soft spot for brunch. I work with local farms and keep things relaxed and generous — the kind of meal that runs long and easy.",
    cuisines: ["New American", "Brunch", "Farm-to-table"],
    dietarySpecialties: ["Vegetarian on request"],
    serviceCity: "Austin",
    serviceRadiusKm: 20,
    neighborhood: "South Congress",
    maxPartySize: 10,
    travelFee: 30,
    ratingAvg: 4.7,
    ratingCount: 27,
    bookingsCompleted: 28,
    status: "approved",
    foodSafetyCertVerified: true,
    insuranceVerified: true,
    idVerified: true,
    stripeAccountId: "acct_demo_lena",
    stripePayoutsEnabled: true,
    availabilityWeekdays: [0, 5, 6],
    leadTimeDays: 2,
    blockedDates: [],
    seed: "lena",
  },
  {
    id: "chef_sam",
    userId: "user_sam",
    displayName: "Sam Okafor",
    tagline: "West African feasts & low-and-slow BBQ",
    bio: "Bold, smoky, spice-driven cooking — jollof done right, suya off the grill, and Texas BBQ technique in the mix. Great for a backyard party that people talk about for months.",
    cuisines: ["West African", "BBQ", "Fusion"],
    dietarySpecialties: ["Halal on request"],
    serviceCity: "Austin",
    serviceRadiusKm: 30,
    neighborhood: "North Loop",
    maxPartySize: 20,
    travelFee: 45,
    ratingAvg: 4.9,
    ratingCount: 14,
    bookingsCompleted: 15,
    status: "approved",
    foodSafetyCertVerified: true,
    insuranceVerified: true,
    idVerified: true,
    stripeAccountId: "acct_demo_sam",
    stripePayoutsEnabled: true,
    availabilityWeekdays: [5, 6, 0],
    leadTimeDays: 3,
    blockedDates: [],
    seed: "sam",
  },
  {
    id: "chef_diego",
    userId: "user_diego",
    displayName: "Diego Santos",
    tagline: "Argentine asado & open-fire cooking",
    bio: "Live-fire asador. Provoleta, chimichurri, whole cuts over wood. Applied this week — pending verification.",
    cuisines: ["Argentine", "Grill", "Latin American"],
    dietarySpecialties: [],
    serviceCity: "Austin",
    serviceRadiusKm: 25,
    neighborhood: "Zilker",
    maxPartySize: 18,
    travelFee: 55,
    ratingAvg: 0,
    ratingCount: 0,
    bookingsCompleted: 0,
    status: "pending",
    foodSafetyCertVerified: false,
    insuranceVerified: false,
    idVerified: false,
    stripeAccountId: null,
    stripePayoutsEnabled: false,
    availabilityWeekdays: [5, 6],
    leadTimeDays: 3,
    blockedDates: [],
    seed: "diego",
  },
];

const menus: Menu[] = [
  {
    id: "menu_ana_italian",
    chefId: "chef_ana",
    name: "Coastal Italian Dinner",
    description: "A four-course seafood-forward menu inspired by the Amalfi coast — bright, simple, made from the best of the market.",
    pricePerGuest: 120,
    minGuests: 4,
    maxGuests: 12,
    dietaryTags: ["Pescatarian", "Gluten-free on request"],
    courses: [
      { name: "Antipasti", dishes: ["Marinated olives & focaccia", "Burrata with summer tomato & basil"] },
      { name: "Primi", dishes: ["Spaghetti alle vongole", "Saffron risotto with prawns"] },
      { name: "Secondi", dishes: ["Whole branzino, lemon & herbs", "Roasted seasonal vegetables"] },
      { name: "Dolci", dishes: ["Lemon olive-oil cake", "Espresso & amaretti"] },
    ],
    seed: "ana-italian",
    isActive: true,
  },
  {
    id: "menu_ana_mezze",
    chefId: "chef_ana",
    name: "Mediterranean Mezze Feast",
    description: "A generous spread of small plates meant for sharing — perfect for a long, social table.",
    pricePerGuest: 95,
    minGuests: 6,
    maxGuests: 14,
    dietaryTags: ["Vegetarian-friendly", "Gluten-free on request"],
    courses: [
      { name: "Dips & breads", dishes: ["Hummus, baba ganoush, muhammara", "Warm pita & za'atar flatbread"] },
      { name: "Hot mezze", dishes: ["Grilled halloumi", "Spiced lamb kofta", "Falafel"] },
      { name: "Mains", dishes: ["Chicken souvlaki", "Charred eggplant & tahini"] },
      { name: "Sweet", dishes: ["Baklava", "Greek yogurt with honey & pistachio"] },
    ],
    seed: "ana-mezze",
    isActive: true,
  },
  {
    id: "menu_marco_steak",
    chefId: "chef_marco",
    name: "Prime Steakhouse Experience",
    description: "Dry-aged beef cooked to temperature, proper sauces, and all the classic sides. A steakhouse dinner without leaving home.",
    pricePerGuest: 145,
    minGuests: 4,
    maxGuests: 10,
    dietaryTags: ["Keto-friendly"],
    courses: [
      { name: "Starter", dishes: ["Wedge salad, blue cheese & bacon", "Seared scallops"] },
      { name: "Main", dishes: ["Dry-aged ribeye", "Béarnaise & peppercorn sauces"] },
      { name: "Sides", dishes: ["Truffle mashed potato", "Creamed spinach", "Charred broccolini"] },
      { name: "Dessert", dishes: ["Dark chocolate torte"] },
    ],
    seed: "marco-steak",
    isActive: true,
  },
  {
    id: "menu_marco_bistro",
    chefId: "chef_marco",
    name: "French Bistro Night",
    description: "Cozy French classics done properly — the kind of meal that makes a Tuesday feel like Paris.",
    pricePerGuest: 110,
    minGuests: 4,
    maxGuests: 10,
    dietaryTags: [],
    courses: [
      { name: "Entrée", dishes: ["French onion soup", "Frisée aux lardons"] },
      { name: "Plat", dishes: ["Coq au vin", "Steak frites"] },
      { name: "Fromage", dishes: ["Selection of French cheeses"] },
      { name: "Dessert", dishes: ["Crème brûlée"] },
    ],
    seed: "marco-bistro",
    isActive: true,
  },
  {
    id: "menu_priya_thali",
    chefId: "chef_priya",
    name: "South Indian Thali",
    description: "A full vegetarian thali — many small dishes, balanced and built to share, finished with house chai.",
    pricePerGuest: 85,
    minGuests: 4,
    maxGuests: 16,
    dietaryTags: ["Vegetarian", "Vegan on request", "Nut-free"],
    courses: [
      { name: "To start", dishes: ["Medu vada", "Tomato rasam"] },
      { name: "Thali", dishes: ["Sambar", "Avial", "Beetroot thoran", "Coconut rice", "Curd rice"] },
      { name: "Breads", dishes: ["Dosa", "Appam"] },
      { name: "Sweet", dishes: ["Payasam", "Masala chai"] },
    ],
    seed: "priya-thali",
    isActive: true,
  },
  {
    id: "menu_priya_tasting",
    chefId: "chef_priya",
    name: "Modern Vegetarian Tasting",
    description: "A plated, multi-course vegetarian tasting menu — refined, seasonal, and full of surprises.",
    pricePerGuest: 105,
    minGuests: 4,
    maxGuests: 10,
    dietaryTags: ["Vegetarian", "Vegan on request"],
    courses: [
      { name: "One", dishes: ["Charred corn shorba"] },
      { name: "Two", dishes: ["Beet & paneer tikka"] },
      { name: "Three", dishes: ["Wild mushroom dosa, truffle"] },
      { name: "Four", dishes: ["Gulab jamun cheesecake"] },
    ],
    seed: "priya-tasting",
    isActive: true,
  },
  {
    id: "menu_lena_supper",
    chefId: "chef_lena",
    name: "Sunday Supper",
    description: "A relaxed, generous family-style dinner built around the farmers' market that week.",
    pricePerGuest: 90,
    minGuests: 4,
    maxGuests: 10,
    dietaryTags: ["Vegetarian on request"],
    courses: [
      { name: "Table", dishes: ["Market salad", "Cultured butter & sourdough"] },
      { name: "Main", dishes: ["Herb-roasted chicken", "Braised short rib"] },
      { name: "Sides", dishes: ["Maple roasted carrots", "Cheddar grits"] },
      { name: "Dessert", dishes: ["Seasonal fruit galette"] },
    ],
    seed: "lena-supper",
    isActive: true,
  },
  {
    id: "menu_lena_brunch",
    chefId: "chef_lena",
    name: "Garden Brunch",
    description: "A leisurely weekend brunch spread for a sunny morning with friends.",
    pricePerGuest: 65,
    minGuests: 6,
    maxGuests: 10,
    dietaryTags: ["Vegetarian-friendly"],
    courses: [
      { name: "Sweet", dishes: ["Ricotta pancakes", "Cinnamon rolls"] },
      { name: "Savory", dishes: ["Soft scramble & chives", "Shakshuka", "Maple breakfast sausage"] },
      { name: "Sides", dishes: ["Hash browns", "Fruit & yogurt"] },
    ],
    seed: "lena-brunch",
    isActive: true,
  },
  {
    id: "menu_sam_feast",
    chefId: "chef_sam",
    name: "West African Feast",
    description: "A vibrant, generous spread — jollof, grilled suya, and all the fixings. Made for a crowd.",
    pricePerGuest: 98,
    minGuests: 6,
    maxGuests: 20,
    dietaryTags: ["Halal on request"],
    courses: [
      { name: "Starters", dishes: ["Suya skewers", "Puff puff", "Kelewele"] },
      { name: "Mains", dishes: ["Smoky jollof rice", "Grilled tilapia", "Chicken in groundnut stew"] },
      { name: "Sides", dishes: ["Fried plantain", "Moi moi"] },
      { name: "Sweet", dishes: ["Coconut chin chin"] },
    ],
    seed: "sam-feast",
    isActive: true,
  },
  {
    id: "menu_sam_bbq",
    chefId: "chef_sam",
    name: "Smoke & Spice BBQ",
    description: "Low-and-slow Texas BBQ with a West African spice twist. Backyard party energy.",
    pricePerGuest: 88,
    minGuests: 8,
    maxGuests: 20,
    dietaryTags: [],
    courses: [
      { name: "Off the smoker", dishes: ["Brisket", "Spiced beef ribs", "Smoked chicken"] },
      { name: "Sides", dishes: ["Mac & cheese", "Charred corn", "Slaw"] },
      { name: "Sweet", dishes: ["Peach cobbler"] },
    ],
    seed: "sam-bbq",
    isActive: true,
  },
  {
    id: "menu_diego_asado",
    chefId: "chef_diego",
    name: "Argentine Asado (draft)",
    description: "Open-fire asado — pending verification before going live.",
    pricePerGuest: 115,
    minGuests: 8,
    maxGuests: 18,
    dietaryTags: [],
    courses: [
      { name: "Fire", dishes: ["Provoleta", "Chorizo & morcilla"] },
      { name: "Cuts", dishes: ["Asado de tira", "Vacío", "Chimichurri"] },
      { name: "Sweet", dishes: ["Dulce de leche flan"] },
    ],
    seed: "diego-asado",
    isActive: false,
  },
];

// ---- Bookings (money snapshotted via the pricing engine) -------------------

function makeBooking(args: {
  id: string;
  clientId: string;
  chefId: string;
  menu: Menu;
  guests: number;
  travelFee: number;
  eventDate: string;
  eventTime: string;
  status: Booking["status"];
  escrow: Booking["escrow"];
  address: Booking["address"];
  allergies: string;
  dietaryNotes?: string;
  specialRequests?: string;
  createdAt: string;
}): Booking {
  const q = computeQuote(args.menu.pricePerGuest, args.guests, args.travelFee);
  return {
    id: args.id,
    clientId: args.clientId,
    chefId: args.chefId,
    menuId: args.menu.id,
    status: args.status,
    eventDate: args.eventDate,
    eventTime: args.eventTime,
    guestCount: args.guests,
    address: args.address,
    allergies: args.allergies,
    dietaryNotes: args.dietaryNotes ?? "",
    specialRequests: args.specialRequests ?? "",
    menuSubtotal: q.menuSubtotal,
    travelFee: q.travelFee,
    subtotal: q.subtotal,
    serviceFee: q.serviceFee,
    tax: q.tax,
    totalCharged: q.totalCharged,
    commission: q.commission,
    chefPayout: q.chefPayout,
    items: q.items,
    escrow: args.escrow,
    createdAt: args.createdAt,
  };
}

const menuById = (id: string) => menus.find((m) => m.id === id)!;

const bookings: Booking[] = [
  makeBooking({
    id: "bk_completed_1",
    clientId: "user_jordan",
    chefId: "chef_ana",
    menu: menuById("menu_ana_italian"),
    guests: 8,
    travelFee: 40,
    eventDate: daysFromNow(-10),
    eventTime: "19:00",
    status: "completed",
    escrow: "released",
    address: { street: "1204 E 6th St", unit: "Loft B", city: "Austin", kitchenNotes: "Gas range, lots of counter space." },
    allergies: "One guest is allergic to shellfish — please keep the prawns separate.",
    dietaryNotes: "One pescatarian (fine with this menu).",
    specialRequests: "It's a birthday — a candle on the dolci would be lovely.",
    createdAt: ts(20),
  }),
  makeBooking({
    id: "bk_confirmed_1",
    clientId: "user_jordan",
    chefId: "chef_marco",
    menu: menuById("menu_marco_bistro"),
    guests: 6,
    travelFee: 50,
    eventDate: daysFromNow(9),
    eventTime: "18:30",
    status: "confirmed",
    escrow: "held",
    address: { street: "88 Westlake Dr", city: "Austin", kitchenNotes: "Induction cooktop." },
    allergies: "No allergies.",
    specialRequests: "Anniversary dinner — keep it unhurried.",
    createdAt: ts(4),
  }),
  makeBooking({
    id: "bk_requested_1",
    clientId: "user_jordan",
    chefId: "chef_ana",
    menu: menuById("menu_ana_mezze"),
    guests: 10,
    travelFee: 40,
    eventDate: daysFromNow(14),
    eventTime: "19:30",
    status: "requested",
    escrow: "authorized",
    address: { street: "1204 E 6th St", unit: "Loft B", city: "Austin" },
    allergies: "Two guests are gluten-free — need GF pita.",
    dietaryNotes: "Mostly vegetarian crowd.",
    specialRequests: "Casual house party, would love it spread out as a grazing table.",
    createdAt: ts(0),
  }),
  makeBooking({
    id: "bk_completed_2",
    clientId: "user_riley",
    chefId: "chef_ana",
    menu: menuById("menu_ana_mezze"),
    guests: 6,
    travelFee: 40,
    eventDate: daysFromNow(-25),
    eventTime: "19:00",
    status: "completed",
    escrow: "released",
    address: { street: "55 Rainey St", city: "Austin" },
    allergies: "Nut allergy — no pistachio on the yogurt please.",
    createdAt: ts(34),
  }),
  makeBooking({
    id: "bk_completed_3",
    clientId: "user_sofia",
    chefId: "chef_marco",
    menu: menuById("menu_marco_steak"),
    guests: 4,
    travelFee: 50,
    eventDate: daysFromNow(-18),
    eventTime: "20:00",
    status: "completed",
    escrow: "released",
    address: { street: "300 Bee Cave Rd", city: "Austin" },
    allergies: "No allergies.",
    createdAt: ts(28),
  }),
  makeBooking({
    id: "bk_completed_4",
    clientId: "user_riley",
    chefId: "chef_priya",
    menu: menuById("menu_priya_thali"),
    guests: 12,
    travelFee: 35,
    eventDate: daysFromNow(-32),
    eventTime: "13:00",
    status: "completed",
    escrow: "released",
    address: { street: "2100 Manor Rd", city: "Austin" },
    allergies: "Strictly nut-free table.",
    createdAt: ts(40),
  }),
];

const messages: Message[] = [
  { id: "msg_1", bookingId: "bk_completed_1", senderId: "user_jordan", body: "Hi Ana! So excited for Saturday. The shellfish allergy is important — thank you for flagging you'd keep it separate.", createdAt: ts(18) },
  { id: "msg_2", bookingId: "bk_completed_1", senderId: "user_ana", body: "Of course! I'll plate that guest's primi without prawns and keep boards separate. Do you have a large serving platter I can use for the branzino?", createdAt: ts(18) },
  { id: "msg_3", bookingId: "bk_completed_1", senderId: "user_jordan", body: "Yes, two big ones. See you at 7!", createdAt: ts(17) },
  { id: "msg_4", bookingId: "bk_confirmed_1", senderId: "user_marco", body: "Confirmed for the 30th — thank you! Any wine you'd like me to plan the courses around?", createdAt: ts(3) },
  { id: "msg_5", bookingId: "bk_confirmed_1", senderId: "user_jordan", body: "We'll have a Burgundy open. Coq au vin sounds perfect with it.", createdAt: ts(3) },
];

const reviews: Review[] = [
  {
    id: "rev_1",
    bookingId: "bk_completed_1",
    authorId: "user_jordan",
    direction: "client_to_chef",
    ratingFood: 5,
    ratingPresentation: 5,
    ratingProfessionalism: 5,
    ratingCommunication: 5,
    comment: "Genuinely one of the best meals we've had, in our own dining room. Ana was warm, organized, and the kitchen was spotless when she left. The branzino was perfect.",
    isVisible: true,
    createdAt: ts(9),
  },
  {
    id: "rev_2",
    bookingId: "bk_completed_1",
    authorId: "user_ana",
    direction: "chef_to_client",
    ratingCommunication: 5,
    comment: "Wonderful hosts, lovely kitchen, clear about the allergy. Would happily cook for them again.",
    isVisible: true,
    createdAt: ts(9),
  },
  {
    id: "rev_3",
    bookingId: "bk_completed_2",
    authorId: "user_riley",
    direction: "client_to_chef",
    ratingFood: 5,
    ratingPresentation: 4,
    ratingProfessionalism: 5,
    ratingCommunication: 5,
    comment: "The mezze spread was beautiful and everyone went back for thirds. Super accommodating with the nut allergy.",
    isVisible: true,
    createdAt: ts(24),
  },
  {
    id: "rev_4",
    bookingId: "bk_completed_3",
    authorId: "user_sofia",
    direction: "client_to_chef",
    ratingFood: 5,
    ratingPresentation: 5,
    ratingProfessionalism: 4,
    ratingCommunication: 5,
    comment: "Restaurant-quality ribeye and the béarnaise was incredible. Marco runs a tight, professional service.",
    isVisible: true,
    createdAt: ts(17),
  },
  {
    id: "rev_5",
    bookingId: "bk_completed_4",
    authorId: "user_riley",
    direction: "client_to_chef",
    ratingFood: 5,
    ratingPresentation: 5,
    ratingProfessionalism: 5,
    ratingCommunication: 5,
    comment: "The thali was a feast — so many dishes, all of them excellent, and a completely nut-free table as promised. Booked again already.",
    isVisible: true,
    createdAt: ts(31),
  },
];

const applications: ChefApplication[] = [
  {
    id: "app_diego",
    name: "Diego Santos",
    city: "Austin",
    email: "diego@example.com",
    phone: "+1512000333",
    yearsCooking: "12",
    cuisines: "Argentine, open-fire grill, Latin American",
    links: "instagram.com/diego.asado",
    hasFoodSafetyCert: "working_on_it",
    hasInsurance: "need_help",
    workTypes: ["events", "dinners"],
    about: "Live-fire asador, 12 years. Looking to bring proper asado to Austin backyards.",
    status: "submitted",
    createdAt: ts(3),
  },
  {
    id: "app_tomas",
    name: "Tomás Vega",
    city: "Austin",
    email: "tomas@example.com",
    phone: "+1512000444",
    yearsCooking: "8",
    cuisines: "Oaxacan, Mexican, moles",
    links: "tomasvega.cooks",
    hasFoodSafetyCert: "yes",
    hasInsurance: "yes",
    workTypes: ["dinners", "meal_prep"],
    about: "Specialize in regional Oaxacan cooking, seven moles. Have my own clientele I'd love to migrate.",
    status: "submitted",
    createdAt: ts(1),
  },
];

const waitlist: WaitlistEntry[] = [
  { id: "wl_1", email: "denver-foodie@example.com", city: "Denver", createdAt: ts(5) },
  { id: "wl_2", email: "nashville@example.com", city: "Nashville", createdAt: ts(2) },
];

export function freshSeed(): DB {
  // structuredClone so the persisted store never aliases these module constants
  return structuredClone({
    users,
    chefs,
    menus,
    bookings,
    messages,
    reviews,
    applications,
    waitlist,
  });
}
